import javafx.embed.swing.JFXPanel;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.List;


public class MusicPlayer extends JFrame implements ActionListener {
    boolean checkStatus = false;
    private int toolbarIconsWidth = 20;
    private int toolbarIconsHeight = 20;
    private JLabel songLabel;
    private Container container;
    private JButton playBtn, pauseBtn, nextBtn, previousBtn;
    List<String> songPaths;
    // icons
    private ImageIcon playIcon, nextIcon, previousIcon, pauseIcon;

    // Sidebar components
    private SidebarPanel sidebarPanel;
    private RightPanel rightPanel;
    MediaManager mediaManager;

    public MusicPlayer() {
        // initialize SongList Class
        Toolkit tk=Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        setTitle("Odtwarzacz muzyczny");
        setSize(screenSize.width/2, screenSize.height/2);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);

        UIManager.put("text", Color.WHITE);
        // Container
        container = getContentPane();
        container.setLayout(new BorderLayout());

        // Sidebars
        sidebarPanel = new SidebarPanel();
        rightPanel = new RightPanel();

        SongList songsList = new SongList("");
        songPaths = songsList.getSongPaths(); // Get songs from SongList Class
        mediaManager = new MediaManager(songPaths);
        refreshTable(mediaManager);

        // Icons - Generated by IconGenerator Class
        IconGenerator iconGenerator = new IconGenerator(toolbarIconsWidth, toolbarIconsHeight);
        playIcon = iconGenerator.createIcon("./resources/play.png");
        nextIcon = iconGenerator.createIcon("./resources/next.png");
        previousIcon = iconGenerator.createIcon("./resources/previous.png");
        pauseIcon = iconGenerator.createIcon("./resources/pause.png");

        // Music control btns
        playBtn = new JButton(playIcon);
        previousBtn = new JButton(previousIcon);
        nextBtn = new JButton(nextIcon);
        pauseBtn = new JButton(pauseIcon);
        JButton testBtn = new JButton("pauseIcon");
        testBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                songsList.setSongsFilePath("songPaths.txt");
                songPaths = songsList.getSongPaths();
                mediaManager.setSongPaths(songPaths);
                refreshTable(mediaManager);
            }
        });

        songLabel = new JLabel();

        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new FlowLayout(FlowLayout.CENTER));

        buttonPanel.add(previousBtn);
        buttonPanel.add(playBtn);
        buttonPanel.add(nextBtn);
        buttonPanel.add(testBtn);

        JPanel songPanel = new JPanel(new BorderLayout());
        songPanel.add(songLabel, BorderLayout.NORTH);
        songPanel.add(buttonPanel, BorderLayout.CENTER);
        playBtn.setIcon(checkStatus ? playIcon : pauseIcon);

        checkStatus =  mediaManager.getMediaPlayerStatus();

        // Music controls - Action Listeners
        playBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mediaManager.stopSong();

                checkStatus = !checkStatus;
                playBtn.setIcon(checkStatus ? playIcon : pauseIcon);
            }
        });

        nextBtn.addActionListener(e->mediaManager.playNextSong());
        previousBtn.addActionListener(e->mediaManager.playPreviousSong());

        // Change BG color of Music Control panel
        buttonPanel.setBackground(Color.decode("#34495E"));

        JProgressBar progressBar = new JProgressBar();
        progressBar.setValue(50);

        JPanel bottomPanel = new JPanel(new BorderLayout());
        bottomPanel.add(songPanel, BorderLayout.NORTH);
        bottomPanel.add(progressBar, BorderLayout.CENTER);

        // !! Important !! Initialize JavaFX Panel - Allow to play music


        // UI Container - Components
        container.add(sidebarPanel, BorderLayout.WEST);
        container.add(rightPanel, BorderLayout.EAST);

        container.add(bottomPanel, BorderLayout.SOUTH);
//        container.add(fxPanel, BorderLayout.PAGE_START);
        container.setForeground(Color.WHITE);

        setVisible(true);
    }

    public static void main(String[] args) {
        // initialize main class
        new MusicPlayer();
    }

    public void refreshTable(MediaManager mediaManager) {
        String[] columnNames = {"Nazwa", "Autor", "Play", "Serduszko"};
        Object[][] data = new Object[songPaths.size()][4];

        for (int i = 0; i < songPaths.size(); i++) {
            String songPath = songPaths.get(i);
            String songName = new File(songPath).getName().replace(".mp3", "");
            Song song = new Song(songName, songPath, false);

            String songLabel = song.getSongName();
            String songAuthor = song.getSongPath();
            JButton playButton = new JButton("Play");
            JButton serduszkoButton = new JButton("Serduszko");

            data[i][0] = songLabel;
            data[i][1] = songAuthor;
            data[i][2] = playButton;
            data[i][3] = serduszkoButton;
        }

        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        JTable table = new JTable(model);

        TableColumn playColumn = table.getColumnModel().getColumn(2);
        playColumn.setCellRenderer(new ButtonRenderer());
        playColumn.setCellEditor(new ButtonEditor(new JCheckBox(), model, table, mediaManager));

        TableColumn serduszkoColumn = table.getColumnModel().getColumn(3);
        serduszkoColumn.setCellRenderer(new ButtonRenderer());
        serduszkoColumn.setCellEditor(new ButtonEditor(new JCheckBox(), model, table, mediaManager));

        container.add(table, BorderLayout.CENTER);

    }
    @Override
    public void actionPerformed(ActionEvent e) {

    }
}



